type Test
    @entity(table: "test", singular: "Test", plural: "Tests")
    @auth(
        getOneRoles: [{ role: ADMIN }, { role: USER }, { role: NONE }]
        getAllRoles: [{ role: ADMIN }, { role: USER }, { role: NONE }]
        createRoles: [{ role: ADMIN }, { role: USER }, { role: NONE }]
        updateRoles: [{ role: ADMIN }, { role: USER }, { role: NONE }]
        deleteRoles: [{ role: ADMIN }, { role: USER }, { role: NONE }]
    )
    @generate(getOne: true, getAll: true, create: true, update: true, delete: true) {
    id: Int! @column @id
    testId: Int @column
    name: String! @column

    parent: Test! @relation(relationType: MANY_TO_ONE, column: "testId", fkTable: "test", fkColumn: "id")
    childrens: [Test!]! @relation(relationType: ONE_TO_MANY, column: "id", fkTable: "test", fkColumn: "testId")
}
